### ISSUE TITLE
error: cannot find -lOnvifDiscoveryLib

### ISSUE THREAD

**Issue by 9friday** [hummatli/onvif-qt-server-client#4]
Hi, 
I am trying to run "ONVIF-QT-SERVER-CLIENT" using QT Creator on Ubuntu-17 64-bit machine. I encounter this error while building my project. 

`:-1: error: cannot find -lOnvifDiscoveryLib`
`:-2: error: cannot find -lOnvifDeviceLib`
`:-3: error: cannot find -lOnvifEventLib`
`:-4: error: cannot find -lOnvifAnalyticsLib`
`:-5: error: cannot find -lOnvifMediaLib`
`:-6: error: cannot find -lOnvifPTZLib`
`:-7: error: cannot find -lOnvifImagingLib`
`:-8: error: collect2: error: ld returned 1 exit status`

I have also uploaded a screenshot:

![onvif-qt-server-client_screenshot](https://user-images.githubusercontent.com/37792181/45211278-7a8ecd00-b2af-11e8-82e6-ff5b1ff15bae.png)

Please tell me if any more information is needed. 

I would be really grateful if someone can help me resolve this error.
Cheers :)

**Comment by WesleyBlq** [comment]
Have you solved this problem? add Q_DECL_EXPORT?

**Comment by 9friday** [comment]
Actually, the issue has been resolved. Theere was an issue with the way it was being compiled.
Thank you. :)

**Comment by ra30** [comment]
Hi, Can anyone send me the working code. 
I am unable to compile the server code.
@9friday  :PLease can you share your working code.
 @taotaochanghe : In which files, should I add Q_DECL_EXPORT?

**Comment by 9friday** [comment]
I am able to 'sendProbe'. But, I am unable to get any response from the
other buttons and the code either hangs or crashes when I click on
'getDeviceInformation'.

**Comment by ra30** [comment]
@9friday : I am unable to compile the server code. It gives me many linker issues.

**Comment by 9friday** [comment]
Did you compile onviflibs?

**Comment by ra30** [comment]
Yes..I did..It was compiled successfully.

**Comment by ra30** [comment]
@9friday : Can you please send me your server code?

**Comment by 9friday** [comment]
Exact same as the one in the repo.

**Comment by ra30** [comment]
@9friday : But, I ma unable to compile the code. It gives me many error.
Eg: onvifserverthread.obj : error LNK2019: unresolved external symbol soap_bind referenced in function "protected: virtual void __cdecl OnvifServerThread::run(void)" (?run@OnvifServerThread@@MEAAXXZ)
I have successfully compiled the onviflibs. 

Can you please guide me or tell me the steps you followed before compiling the code?

**Comment by ra30** [comment]
@9friday : I am unable to compile the server code. Wherever I use soap related function, it gives me error.
  E.g: char* _endpoint= (char*)**soap_wsa_rand_uuid**(serv); ---->
Error msg:
 **onvifserverthread.obj : error LNK2019: unresolved external symbol soap_wsa_rand_uuid referenced in function "protected: virtual void __cdecl OnvifServerThread::run(void)" (?run@OnvifServerThread@@MEAAXXZ)**
Could you please help me.
Which compiler are you using?

**Comment by ra30** [comment]
@9friday ,@taotaochanghe : I resolved the error. the client application lists the devices. 
Now if I want to set the information (e.g.: firmware version etc) of server, how can I do it?

**Comment by hrdzkj** [comment]
请问就下面这个问题，怎么解决呀？
-1: error: cannot find -lOnvifDiscoveryLib
:-2: error: cannot find -lOnvifDeviceLib
:-3: error: cannot find -lOnvifEventLib
:-4: error: cannot find -lOnvifAnalyticsLib
:-5: error: cannot find -lOnvifMediaLib
:-6: error: cannot find -lOnvifPTZLib
:-7: error: cannot find -lOnvifImagingLib
:-8: error: collect2: error: ld returned 1 exit status

**Comment by hrdzkj** [comment]
@9friday Please tell me how to solve this problem？

**Comment by p3im4n** [comment]
> @9friday Please tell me how to solve this problem？

hi
bulid for release
and  add this term to any pro file:
DEFINES += SOAP_STD_EXPORTS
them build one by one
